<a href="https://colab.research.google.com/github/s-caro/psychic-broccoli/blob/main/Create_Hamiltonian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [113]:
import numpy as np
import pandas as pd
import math
import pprint

In [80]:
from sympy import Matrix

from sympy.physics.quantum import TensorProduct

In [81]:
a = np.array(range(1,5))
a.shape = (2,2)

In [82]:
a

array([[1, 2],
       [3, 4]])

In [83]:
b = np.array(range(5,9))
b.shape = (2,2)
b

array([[5, 6],
       [7, 8]])

In [84]:
np.tensordot(a,b,axes=0)

array([[[[ 5,  6],
         [ 7,  8]],

        [[10, 12],
         [14, 16]]],


       [[[15, 18],
         [21, 24]],

        [[20, 24],
         [28, 32]]]])

In [85]:
a = np.array([1,0,0,1])
a.shape = (2,2)
b = np.array([0,0,0,1])
b.shape = (2,2)
print(a)
print(b)

[[1 0]
 [0 1]]
[[0 0]
 [0 1]]


In [86]:
np.tensordot(a,b,axes=0)

array([[[[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]]]])

In [87]:
I = np.identity(2)

In [88]:
s_x = np.matrix([[0,1],[1,0]])
s_z = np.matrix([[1,0],[0,-1]])
spin_z = (I-s_z)/2

In [89]:
spin_z

matrix([[0., 0.],
        [0., 1.]])

In [90]:
H_f = 5*(np.tensordot(spin_z,I,axes=0)) + np.tensordot(I,spin_z,axes=0) - 2*(np.tensordot(spin_z,spin_z, axes=0))

In [91]:
H_f

array([[[[0., 0.],
         [0., 1.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[5., 0.],
         [0., 4.]]]])

In [92]:
type(H_f)

numpy.ndarray

In [93]:
H_f.shape

(2, 2, 2, 2)

In [94]:
H_f.shape = (4,4)

In [95]:
H_f

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [5., 0., 0., 4.]])

In [96]:
I = Matrix([[1,0],[0,1]])
I

Matrix([
[1, 0],
[0, 1]])

In [97]:
s_z = Matrix([[1,0],[0,-1]])
s_z

Matrix([
[1,  0],
[0, -1]])

In [98]:
spin_z = (I-s_z)/2
spin_z

Matrix([
[0, 0],
[0, 1]])

In [99]:
TensorProduct(I,spin_z)

Matrix([
[0, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 1]])

In [100]:
H_f = 5*TensorProduct(spin_z, I) + TensorProduct(I, spin_z) - 2*(TensorProduct(spin_z, spin_z))

In [101]:
H_f

Matrix([
[0, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 5, 0],
[0, 0, 0, 4]])

**Formulazione e Hamiltoniana di un max-cut**

*La soluzione dovrebbe essere (0,1,1,0,0)*

In [102]:
H_max_cut = 2*TensorProduct(spin_z,I,I,I,I) + 2*TensorProduct(I,spin_z,I,I,I) + 3*TensorProduct(I,I,spin_z,I,I) + 3*TensorProduct(I,I,I,spin_z,I) + 2*TensorProduct(I,I,I,I,spin_z)- 2*TensorProduct(spin_z,spin_z,I,I,I) - 2*TensorProduct(spin_z,I,spin_z,I,I) -2*TensorProduct(I,spin_z,I,spin_z,I) - 2*TensorProduct(I,I,spin_z,spin_z,I) - 2*TensorProduct(I,I,spin_z,I,spin_z) - 2*TensorProduct(I,I,I,spin_z,spin_z)

f(x) = 2$x_1$ + 2$x_2$ + 3$x_3$ + 3$x_4$ + 2$x_5$ - 2$x_1x_2$ - 2$x_1x_3$ - 2$x_2x_4$ -2$x_3x_4$ -2$x_3x_5$ - 2$x_4x_5$

In [103]:
H_max_cut

Matrix([
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0

In [104]:
H_max_cut.eigenvals()

{0: 2, 2: 8, 3: 12, 4: 6, 5: 4}

In [ ]:
H_max_cut.eigenvects()[4]

In [105]:
s_x = Matrix([[0,1],[1,0]])
s_x

Matrix([
[0, 1],
[1, 0]])

In [107]:
spin_x = (I-s_x)/2
spin_x

Matrix([
[ 1/2, -1/2],
[-1/2,  1/2]])

In [109]:
H_in = TensorProduct(spin_x, I) + TensorProduct(I,spin_x)
H_in

Matrix([
[   1, -1/2, -1/2,    0],
[-1/2,    1,    0, -1/2],
[-1/2,    0,    1, -1/2],
[   0, -1/2, -1/2,    1]])

In [110]:
H_in.eigenvals()

{2: 1, 1: 2, 0: 1}

In [111]:
H_in.eigenvects()

[(0, 1, [Matrix([
   [1],
   [1],
   [1],
   [1]])]), (1, 2, [Matrix([
   [ 0],
   [-1],
   [ 1],
   [ 0]]), Matrix([
   [-1],
   [ 0],
   [ 0],
   [ 1]])]), (2, 1, [Matrix([
   [ 1],
   [-1],
   [-1],
   [ 1]])])]

In [115]:
H_in = TensorProduct(spin_x, I,I) + TensorProduct(I,spin_x,I) + TensorProduct(I,I,spin_x)
H_in

Matrix([
[ 3/2, -1/2, -1/2,    0, -1/2,    0,    0,    0],
[-1/2,  3/2,    0, -1/2,    0, -1/2,    0,    0],
[-1/2,    0,  3/2, -1/2,    0,    0, -1/2,    0],
[   0, -1/2, -1/2,  3/2,    0,    0,    0, -1/2],
[-1/2,    0,    0,    0,  3/2, -1/2, -1/2,    0],
[   0, -1/2,    0,    0, -1/2,  3/2,    0, -1/2],
[   0,    0, -1/2,    0, -1/2,    0,  3/2, -1/2],
[   0,    0,    0, -1/2,    0, -1/2, -1/2,  3/2]])

In [118]:
H_in.eigenvals()

{3: 1, 2: 3, 1: 3, 0: 1}

In [117]:
H_in.eigenvects()[0]

(0, 1, [Matrix([
  [1],
  [1],
  [1],
  [1],
  [1],
  [1],
  [1],
  [1]])])

In [119]:
H_in = TensorProduct(spin_x, I,I,I) + TensorProduct(I,spin_x,I,I) + TensorProduct(I,I,spin_x,I) + TensorProduct(I,I,I,spin_x)
H_in

Matrix([
[   2, -1/2, -1/2,    0, -1/2,    0,    0,    0, -1/2,    0,    0,    0,    0,    0,    0,    0],
[-1/2,    2,    0, -1/2,    0, -1/2,    0,    0,    0, -1/2,    0,    0,    0,    0,    0,    0],
[-1/2,    0,    2, -1/2,    0,    0, -1/2,    0,    0,    0, -1/2,    0,    0,    0,    0,    0],
[   0, -1/2, -1/2,    2,    0,    0,    0, -1/2,    0,    0,    0, -1/2,    0,    0,    0,    0],
[-1/2,    0,    0,    0,    2, -1/2, -1/2,    0,    0,    0,    0,    0, -1/2,    0,    0,    0],
[   0, -1/2,    0,    0, -1/2,    2,    0, -1/2,    0,    0,    0,    0,    0, -1/2,    0,    0],
[   0,    0, -1/2,    0, -1/2,    0,    2, -1/2,    0,    0,    0,    0,    0,    0, -1/2,    0],
[   0,    0,    0, -1/2,    0, -1/2, -1/2,    2,    0,    0,    0,    0,    0,    0,    0, -1/2],
[-1/2,    0,    0,    0,    0,    0,    0,    0,    2, -1/2, -1/2,    0, -1/2,    0,    0,    0],
[   0, -1/2,    0,    0,    0,    0,    0,    0, -1/2,    2,    0, -1/2,    0, -1/2,    0,    0],
[   0,    0

In [120]:
H_in.eigenvals()

{4: 1, 3: 4, 1: 4, 2: 6, 0: 1}

In [121]:
H_in.eigenvects()[0]

(0, 1, [Matrix([
  [1],
  [1],
  [1],
  [1],
  [1],
  [1],
  [1],
  [1],
  [1],
  [1],
  [1],
  [1],
  [1],
  [1],
  [1],
  [1]])])