<a href="https://colab.research.google.com/github/s-caro/psychic-broccoli/blob/main/Create_Hamiltonian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np
import pandas as pd
import math

In [50]:
from sympy import Matrix

from sympy.physics.quantum import TensorProduct

In [3]:
a = np.array(range(1,5))
a.shape = (2,2)

In [4]:
a

array([[1, 2],
       [3, 4]])

In [10]:
b = np.array(range(5,9))
b.shape = (2,2)
b

array([[5, 6],
       [7, 8]])

In [11]:
np.tensordot(a,b,axes=0)

array([[[[ 5,  6],
         [ 7,  8]],

        [[10, 12],
         [14, 16]]],


       [[[15, 18],
         [21, 24]],

        [[20, 24],
         [28, 32]]]])

In [13]:
a = np.array([1,0,0,1])
a.shape = (2,2)
b = np.array([0,0,0,1])
b.shape = (2,2)
print(a)
print(b)

[[1 0]
 [0 1]]
[[0 0]
 [0 1]]


In [15]:
np.tensordot(a,b,axes=0)

array([[[[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]]]])

In [20]:
I = np.identity(2)

In [21]:
s_x = np.matrix([[0,1],[1,0]])
s_z = np.matrix([[1,0],[0,-1]])
spin_z = (I-s_z)/2

In [22]:
spin_z

matrix([[0., 0.],
        [0., 1.]])

In [23]:
H_f = 5*(np.tensordot(spin_z,I,axes=0)) + np.tensordot(I,spin_z,axes=0) - 2*(np.tensordot(spin_z,spin_z, axes=0))

In [24]:
H_f

array([[[[0., 0.],
         [0., 1.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[5., 0.],
         [0., 4.]]]])

In [27]:
type(H_f)

numpy.ndarray

In [28]:
H_f.shape

(2, 2, 2, 2)

In [29]:
H_f.shape = (4,4)

In [30]:
H_f

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [5., 0., 0., 4.]])

In [62]:
I = Matrix([[1,0],[0,1]])
I

Matrix([
[1, 0],
[0, 1]])

In [36]:
s_z = Matrix([[1,0],[0,-1]])
s_z

Matrix([
[1,  0],
[0, -1]])

In [63]:
spin_z = (I-s_z)/2
spin_z

Matrix([
[0, 0],
[0, 1]])

In [38]:
TensorProduct(I,spin_z)

Matrix([
[0, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 1]])

In [39]:
H_f = 5*TensorProduct(spin_z, I) + TensorProduct(I, spin_z) - 2*(TensorProduct(spin_z, spin_z))

In [40]:
H_f

Matrix([
[0, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 5, 0],
[0, 0, 0, 4]])

**Formulazione e Hamiltoniana di un max-cut**

*La soluzione dovrebbe essere (0,1,1,0,0)*

In [41]:
H_max_cut = 2*TensorProduct(spin_z,I,I,I,I) + 2*TensorProduct(I,spin_z,I,I,I) + 3*TensorProduct(I,I,spin_z,I,I) + 3*TensorProduct(I,I,I,spin_z,I) + 2*TensorProduct(I,I,I,I,spin_z)- 2*TensorProduct(spin_z,spin_z,I,I,I) - 2*TensorProduct(spin_z,I,spin_z,I,I) -2*TensorProduct(I,spin_z,I,spin_z,I) - 2*TensorProduct(I,I,spin_z,spin_z,I) - 2*TensorProduct(I,I,spin_z,I,spin_z) - 2*TensorProduct(I,I,I,spin_z,spin_z)

f(x) = 2$x_1$ + 2$x_2$ + 3$x_3$ + 3$x_4$ + 2$x_5$ - 2$x_1x_2$ - 2$x_1x_3$ - 2$x_2x_4$ -2$x_3x_4$ -2$x_3x_5$ - 2$x_4x_5$

In [42]:
H_max_cut

Matrix([
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0

In [56]:
H_max_cut.eigenvals()

{0: 2, 2: 8, 3: 12, 4: 6, 5: 4}